language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

sudo: required

install:
  - ./travis/install-cassandra-driver.sh

services:
  - cassandra

before_script:
  - cqlsh -f travis/create-schema.cql

after_script:
  - cqlsh -f travis/drop-schema.cql

script:
  - phpunit tests --bootstrap vendor/autoload.php
